name: Deploy Azure WebApp

inputs:
  resource_group:
    required: true
  web_app_name:
    required: true
  artifact_name:
    required: true
  azure_credentials:
    required: true

runs:
  using: "composite"
  steps:
  - name: Download Artifact
    uses: actions/download-artifact@v2
    with:
      name: ${{ env.artifact_name }}
      
  - name: Zip package
    shell: bash
    run: | 
      ls 
      echo "--END---"
      zip -r ./${{ inputs.artifact_name }} .
      ls   
      echo "--END---"     

  - name: Login to Azure
    uses: azure/login@v1
    with:
      creds: '${{ inputs.azure_credentials }}'

  - name: Deploy to QA
    shell: bash
    run: |
      az webapp deployment source config-zip --resource-group ${{ inputs.resource_group }} --name ${{ inputs.web_app_name }} --src ${{ inputs.artifact_name }}/${{ inputs.artifact_name }}.zip
