name: Common SDeployment

on: [push]

jobs:
  common-deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.PUBLISH_OUTPUT_PATH }}
        
    - name: Zip package
      run: | 
        cd ${{ env.PUBLISH_OUTPUT_PATH }}
        zip -r ./${{ env.ARTIFACT_NAME }} .
        ls        

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

  #   # - name: Configure Environmental Variables
  #   #   run: |
  #   #     az webapp config appsettings set --resource-group ${{ vars.RESOURCE_GROUP }} --name ${{ vars.WEB_APP_NAME }} --settings "<KEY>"=<VALUE>

    - name: Deploy to QA
      run: |
        az webapp deployment source config-zip --resource-group ${{ vars.RESOURCE_GROUP }} --name ${{ vars.WEB_APP_NAME_2 }} --src ${{ env.PUBLISH_OUTPUT_PATH }}/${{ env.ARTIFACT_NAME }}.zip
