name: CI/CD

on: push

env:
  SOLUTION_PATH: './WebApplication1.sln'
  BUILD_CONFIG: 'Release'
  DOTNET_VERSION: '6.0.x'
  PUBLISH_OUTPUT_PATH: './published'
  ARTIFACT_NAME: 'application'



jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore packages
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration ${{ env.BUILD_CONFIG }}

    - name: Publish
      run: dotnet publish ${{ env.SOLUTION_PATH }} --configuration ${{ env.BUILD_CONFIG }} -o ${{ env.PUBLISH_OUTPUT_PATH }}

    - name: Zip package
      run: | 
        cd ${{ env.PUBLISH_OUTPUT_PATH }}
        zip -r ../${{ env.ARTIFACT_NAME }} .

  # deploy-dev:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/develop'
  #   steps:
  #   - name: Deploy to Dev
  #     run: |
  #       # Add your deployment script here
  #       # Example for Azure Web App deployment
  #       # az webapp deployment source config-zip --resource-group YourResourceGroup --name YourWebAppName --src ./bin/Release/netcoreapp3.1/publish.zip
  #     env:
  #       AZURE_WEBAPP_NAME: your-dev-app-name
  #       AZURE_RESOURCE_GROUP: your-dev-resource-group

  # deploy-qa:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #   - name: Deploy to QA
  #     run: |
  #       # Add your deployment script here
  #     env:
  #       AZURE_WEBAPP_NAME: your-qa-app-name
  #       AZURE_RESOURCE_GROUP: your-qa-resource-group

  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Deploy to Prod
  #     run: |
  #       # Add your deployment script here
  #     env:
  #       AZURE_WEBAPP_NAME: your-prod-app-name
  #       AZURE_RESOURCE_GROUP: your-prod-resource-group

  #   - name: Create Release
  #     id: create_release
  #     uses: actions/create-release@v1
  #     with:
  #       tag_name: ${{ github.sha }}
  #       release_name: Release ${{ github.sha }}
  #       draft: false
  #       prerelease: false
